nameOverride: ""
fullnameOverride: ""

image:
  repository: dmarshaltu/argocd-monitor
  tag: latest
  pullPolicy: Always

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

argocd:
  namespace: default
  adminPassword: "aEVNS9sRlf"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}

replicaCount: 1