apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-monitor.fullname" . }}
  labels:
    {{- include "argocd-monitor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "argocd-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "argocd-monitor.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "argocd-monitor.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ARGOCD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "argocd-monitor.fullname" . }}-admin
                  key: password
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}