{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "argocd-monitor.fullname" . }}
  namespace: {{ .Values.argocd.namespace }}
  labels:
    {{- include "argocd-monitor.labels" . | nindent 4 }}
rules:
- apiGroups: ["argoproj.io"]
  resources: ["applications"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "argocd-monitor.fullname" . }}
  namespace: {{ .Values.argocd.namespace }}
  labels:
    {{- include "argocd-monitor.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "argocd-monitor.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "argocd-monitor.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}