apiVersion: v1
kind: Secret
metadata:
  name: {{ include "argocd-monitor.fullname" . }}-admin
  labels:
    {{- include "argocd-monitor.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.argocd.adminPassword | b64enc }}