{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argocd-monitor.serviceAccountName" . }}
  labels:
    {{- include "argocd-monitor.labels" . | nindent 4 }}
{{- end }}